all: clean dirs


dirs:
	@mkdir ./bin && echo "Made" || "Exists Alreaddy!" 
	@mkdir ./obj && echo "Made" || "Exists Alreaddy!" 
	@mkdir ./lib && echo "Made" || "Exists Alreaddy!" 

clean:
	@rm -rf ./bin && echo "Removed" || echo "Does not exist!"
	@rm -rf ./obj && echo "Removed" || echo "Does not exist!"
	@rm -rf ./lib && echo "Removed" || echo "Does not exist!"
  
